### ISSUE TITLE
O que deveria conter no readme.md?

### ISSUE THREAD

**Issue by felquis** [stone-payments/stoneco-guidelines#11]
Olá pessoal, creio que já temos algumas ideias que respondem a pergunta "O que deve conter neste README.md" estou abrindo essa issue, para que a gente discuta:

> O que deve conter em um bom readme.md?

E resultar em um Pull Request adicionando essas dicas tanto em PT-BR quanto EN

Att.

**Comment by patrickporto** [comment]
Eu acredito que essa seja uma boa referência:
https://github.com/noffle/art-of-readme
https://github.com/noffle/art-of-readme/blob/master/README-pt-BR.md

**Comment by endersonmenezes** [comment]
Estamos encerrando esta Issue devido à inatividade. Caso ainda tenha dúvidas, por favor, entre em contato através de um dos nossos canais de atendimento. Estamos atualizando este repositório para servir melhor nossa comunidade de desenvolvedores, tanto internos quanto externos.
