### ISSUE TITLE
Curiosidade

### ISSUE THREAD

**Issue by pettomartino** [stone-payments/stoneco-guidelines#23]
Por que motivos o aplicativo da Conta Stone não estaria disponível em outros países enquanto outros apps da Stone e outros bancos estão?

Acho que poderiam compartilhar configurações entre projetos :)

**Comment by jcaiqueoliveira** [comment]
Hoje o app segue a whitelist de ips da api

**Comment by endersonmenezes** [comment]
Estamos encerrando esta Issue devido à inatividade. Caso ainda tenha dúvidas, por favor, entre em contato através de um dos nossos canais de atendimento. Estamos atualizando este repositório para servir melhor nossa comunidade de desenvolvedores, tanto internos quanto externos.
