### ISSUE TITLE
Link LICENSE sem destino (404)

### ISSUE THREAD

**Issue by rafasalo** [stone-payments/stoneco-guidelines#9]
Ao clicar no link LICENSE, é encaminhado para uma página 404.
 
https://github.com/stone-payments/dlp-best-practices/blob/master/README_pt.md#licença

https://github.com/stone-payments/dlp-best-practices#license

**Comment by jvpr94** [comment]
@rafasalo obrigado pelo report! Ainda não temos esse documento, mas vou criar um em branco mencionando ser um work in progress para pelo menos indicar o status dele.
